### ISSUE TITLE
按要求装好环境之后报这样的bug，请问是什么原因呢

### ISSUE THREAD

**Issue by shishanya** [RUCAIBox/RecBole-CDR#39]
Traceback (most recent call last):
  File "/home/baoyanghao/.pycharm_helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/baoyanghao/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/baoyanghao/ss/mycode/RecBole-CDR/run_recbole_cdr.py", line 18, in <module>
    run_recbole_cdr(model=args.model, config_file_list=config_file_list)
  File "/home/baoyanghao/ss/mycode/RecBole-CDR/recbole_cdr/quick_start/quick_start.py", line 43, in run_recbole_cdr
    train_data, valid_data, test_data = data_preparation(config, dataset)
  File "/home/baoyanghao/ss/mycode/RecBole-CDR/recbole_cdr/data/utils.py", line 87, in data_preparation
    dataloaders = load_split_dataloaders(config)
  File "/home/baoyanghao/anaconda3/envs/pytorch17/lib/python3.7/site-packages/recbole/data/utils.py", line 78, in load_split_dataloaders
    with open(saved_dataloaders_file, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not CDRConfig

Process finished with exit code 1

**Comment by Wicknight** [comment]
@shishanya 您好，这是由于主库RecBole版本落后于RecBole-CDR的开发版本导致的bug，目前我们已经在requirements中进行了更新，麻烦您按照requirements重新安装1.0.1版本RecBole即可。

**Comment by shishanya** [comment]
谢谢您的帮助，问题已经解决了，您这个框架写的真的很好
