### ISSUE TITLE
[🐛BUG] pip install recbole-cdr问题

### ISSUE THREAD

**Issue by 97z** [RUCAIBox/RecBole-CDR#68]
**描述这个 bug**
pip install recbole-cdr会出现一下问题
 error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [149 lines of output]
      setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\Z\AppData\Local\Temp\pip-modern-metadata-5czwbrdp'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      setup.py:563: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

        from numpy.distutils.core import setup
      Running from SciPy source directory.
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_ssl2_info:
      INFO:   libraries fjlapackexsve not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      WARN: Could not locate executable f77
      INFO: customize IntelVisualFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifl
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      INFO: customize CompaqVisualFCompiler
      INFO: Found executable D:\app\git\Git\usr\bin\DF.exe
      INFO: customize IntelItaniumVisualFCompiler
      WARN: Could not locate executable efl
      INFO: customize Gnu95FCompiler
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      INFO: customize G95FCompiler
      WARN: Could not locate executable g95
      INFO: customize IntelEM64VisualFCompiler
      INFO: customize IntelEM64TFCompiler
      WARN: Could not locate executable efort
      WARN: Could not locate executable efc
      INFO: customize PGroupFlangCompiler
      WARN: Could not locate executable flang
      WARN: don't know how to compile Fortran code on platform 'nt'
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in D:\app\anaconda3\download\envs\mygpu\lib
      INFO:   libraries tatlas,tatlas not found in C:\
      INFO:   libraries tatlas,tatlas not found in D:\app\anaconda3\download\envs\mygpu\libs
      INFO:   libraries tatlas,tatlas not found in D:\app\anaconda3\download\Library\lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in D:\app\anaconda3\download\envs\mygpu\lib
      INFO:   libraries satlas,satlas not found in C:\
      INFO:   libraries satlas,satlas not found in D:\app\anaconda3\download\envs\mygpu\libs
      INFO:   libraries satlas,satlas not found in D:\app\anaconda3\download\Library\lib
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in D:\app\anaconda3\download\envs\mygpu\lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in C:\
      INFO:   libraries ptf77blas,ptcblas,atlas not found in D:\app\anaconda3\download\envs\mygpu\libs
      INFO:   libraries ptf77blas,ptcblas,atlas not found in D:\app\anaconda3\download\Library\lib
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in D:\app\anaconda3\download\envs\mygpu\lib
      INFO:   libraries f77blas,cblas,atlas not found in C:\
      INFO:   libraries f77blas,cblas,atlas not found in D:\app\anaconda3\download\envs\mygpu\libs
      INFO:   libraries f77blas,cblas,atlas not found in D:\app\anaconda3\download\Library\lib
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['D:\\app\\anaconda3\\download\\envs\\mygpu\\lib', 'C:\\', 'D:\\app\\anaconda3\\download\\envs\\mygpu\\libs', 'D:\\app\\anaconda3\\download\\Library\\lib']
      INFO:   NOT AVAILABLE
      INFO:
      C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\numpy\distutils\system_info.py:1974: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\numpy\distutils\system_info.py:1974: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      Traceback (most recent call last):
        File "D:\app\anaconda3\download\envs\mygpu\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\app\anaconda3\download\envs\mygpu\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\app\anaconda3\download\envs\mygpu\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel       
          return hook(metadata_directory, config_settings)
        File "C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 588, in <module>
          setup_package()
        File "setup.py", line 584, in setup_package
          setup(**metadata)          raise NotFoundError(msg)
        File "C:\Users\Z\AppData\Local\Temp\pip-build-env-i716z55i\overlay\Lib\site-packages\numpy\distutils\core.py", line 136, in setup
          config = configuration()
        File "setup.py", line 499, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**如何复现**
我看到作者需要的requirements包是recbole==1.0.1，这个包貌似也没法正常安装了。但是我可以正常安装rebole==1.2版本。想问问有没有人也遇到了这个问题。

**实验环境（请补全下列信息）：**
 - 操作系统: [Windows]
- RecBole 版本 [如 1.2.0]
 - Python 版本 [如 3.10.13]
- PyTorch 版本 [如2.1.0]

**Comment by 97z** [comment]
不是clone，直接从git上下载zip文件再用pycharm打开就没问题了。我也没有改环境

**Comment by 97z** [comment]
已经解决了。帮大家避坑。首先recbole需要为1.0.1，1.2.0并不完全兼容，会出现一些小bug。其次，安装recbole1.0.1需要python<3.10。因为scipy需要==1.6.0，这个版本无法支持python3.10
