### ISSUE TITLE
[🐛BUG] Config._set_eval_neg_sample_args() missing 1 required positional argument: 'phase'

### ISSUE THREAD

**Issue by 97z** [RUCAIBox/RecBole-CDR#69]
有人碰到这个bug吗？我直接运行python run_recbole_cdr.py会出现这个bug。其他的内容都没有改。我debug了之后，test.yaml文件里有mode：full这个参数，为啥会报错嘞？
Traceback (most recent call last):
  File "E:\pycharmcode\RecBole-CDR-main\run_recbole_cdr.py", line 22, in <module>
    run_recbole_cdr(model=args.model, config_file_list=config_file_list)
  File "E:\pycharmcode\RecBole-CDR-main\recbole_cdr\quick_start\quick_start.py", line 31, in run_recbole_cdr
    config = CDRConfig(model=model, config_file_list=config_file_list, config_dict=config_dict)
  File "E:\pycharmcode\RecBole-CDR-main\recbole_cdr\config\configurator.py", line 76, in __init__
    self._set_eval_neg_sample_args()
TypeError: Config._set_eval_neg_sample_args() missing 1 required positional argument: 'phase'

**实验环境（请补全下列信息）：**
 - 操作系统: [如 Linux, macOS 或 Windows]
- RecBole 版本 [如1.2.0]
 - Python 版本 [如 3.10]
- PyTorch 版本 [如 2.0.0]

**Comment by 97z** [comment]
当把self._set_eval_neg_sample_args()这句代码改为self._set_eval_neg_sample_args("valid")self._set_eval_neg_sample_args("test")以后，会出现TypeError: string indices must be integers的bug

**Comment by 97z** [comment]
当我修改recbole原函数以后，又会出现log的问题

**Comment by 97z** [comment]
已经解决了。帮大家避坑。首先recbole需要为1.0.1，1.2.0并不完全兼容，会出现一些小bug。其次，安装recbole1.0.1需要python<3.10。因为scipy需要==1.6.0，这个版本无法支持python3.10
